export const schemaData = {
    "ReturnCode": 0,
    "ReturnMessage": "Success",
    "ResponseTime": "136",
    "RecordCount": 0,
    "TemplateName": "",
    "ParentTemplateName": "Vendor",
    "AllTabs": null,
    "APIUrls": [
        {
            "GetBySearchURL": "GetDatabySearch",
            "GetByIdURL": "GetDatabyCode",
            "SaveAPIURL": "SaveData",
            "IsModulePopUp": false,
            "JsonURL": "IMVM-252.Json"
        }
    ],
    "Data": [
        {
            "Type": "toggle",
            "FormField": "IsPublished",
            "Label": "Active",
            "PlaceHolder": "toggle",
            "MasterModuleCode": null,
            "MasterAPIUrl": null,
            "Required": false,
            "RequiredErrorMessage": null,
            "LengthErrorMessage": null,
            "Pattern1": null,
            "Pattern1ErrorMessage": null,
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": null,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": null,
            "ArrayListName": null,
            "ParentFieldName": null,
            "IsView": null,
            "UpdatePublishedProcedureName": "usp_IM_UpdateIMVendorPublishedById",
            "TabName": null,
            "APITemplateName": "Vendor",
            "LabelTooltip": null,
            "IsHideFieldInUI": false
        },
        {
            "Type": "text",
            "FormField": "VendorName",
            "Label": "Vendor Name",
            "PlaceHolder": "Enter Vendor Name",
            "MasterModuleCode": null,
            "MasterAPIUrl": null,
            "Required": true,
            "RequiredErrorMessage": "Enter Vendor Name",
            "LengthErrorMessage": "Vendor Name cannot be more than 128 characters",
            "Pattern1": "^[^<>]*$",
            "Pattern1ErrorMessage": "Invalid Vendor Name",
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": 128,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": null,
            "ArrayListName": null,
            "ParentFieldName": null,
            "IsView": null,
            "UpdatePublishedProcedureName": "usp_IM_UpdateIMVendorPublishedById",
            "TabName": null,
            "APITemplateName": "Vendor",
            "LabelTooltip": "Input the name of your vendor (which could be your Manufacturer, Supplier, Dealer, etc.)",
            "IsHideFieldInUI": false
        },
        {
            "Type": "text",
            "FormField": "VendorCode",
            "Label": "Vendor Code",
            "PlaceHolder": "Enter Vendor Code",
            "MasterModuleCode": null,
            "MasterAPIUrl": null,
            "Required": false,
            "RequiredErrorMessage": "Enter Vendor Code",
            "LengthErrorMessage": "Vendor Code cannot be more than 10 characters",
            "Pattern1": "^[^<>]*$",
            "Pattern1ErrorMessage": "Invalid Vendor Code",
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": 10,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": null,
            "ArrayListName": null,
            "ParentFieldName": null,
            "IsView": null,
            "UpdatePublishedProcedureName": "usp_IM_UpdateIMVendorPublishedById",
            "TabName": null,
            "APITemplateName": "Vendor",
            "LabelTooltip": "Provide a unique code to your vendor for easy identification, especially if multiple vendors share the same name or for other purposes.",
            "IsHideFieldInUI": false
        },
        {
            "Type": "checkbox",
            "FormField": "IsGSTRegistered",
            "Label": "GST Registered",
            "PlaceHolder": "Select GST Registered",
            "MasterModuleCode": null,
            "MasterAPIUrl": null,
            "Required": false,
            "RequiredErrorMessage": null,
            "LengthErrorMessage": null,
            "Pattern1": null,
            "Pattern1ErrorMessage": null,
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": null,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": null,
            "ArrayListName": null,
            "ParentFieldName": null,
            "IsView": null,
            "UpdatePublishedProcedureName": "usp_IM_UpdateIMVendorPublishedById",
            "TabName": null,
            "APITemplateName": "Vendor",
            "LabelTooltip": null,
            "IsHideFieldInUI": false
        },
        {
            "Type": "text",
            "FormField": "ContactFirstName",
            "Label": "Contact First Name",
            "PlaceHolder": "Enter Contact First Name",
            "MasterModuleCode": null,
            "MasterAPIUrl": null,
            "Required": true,
            "RequiredErrorMessage": "Enter Contact First Name",
            "LengthErrorMessage": "Contact First Name cannot be more than 32 characters",
            "Pattern1": "^[^<>]*$",
            "Pattern1ErrorMessage": "Invalid Contact First Name",
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": 32,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": null,
            "ArrayListName": null,
            "ParentFieldName": null,
            "IsView": null,
            "UpdatePublishedProcedureName": "usp_IM_UpdateIMVendorPublishedById",
            "TabName": null,
            "APITemplateName": "Vendor",
            "LabelTooltip": "Enter the first name of the contact person at your vendor's company.",
            "IsHideFieldInUI": false
        },
        {
            "Type": "text",
            "FormField": "ContactLastName",
            "Label": "Contact Last Name",
            "PlaceHolder": "Enter Contact Last Name",
            "MasterModuleCode": null,
            "MasterAPIUrl": null,
            "Required": true,
            "RequiredErrorMessage": "Enter Contact Last Name",
            "LengthErrorMessage": "Contact Last Name cannot be more than 32 characters",
            "Pattern1": "^[^<>]*$",
            "Pattern1ErrorMessage": "Invalid Contact Last Name",
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": 32,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": null,
            "ArrayListName": null,
            "ParentFieldName": null,
            "IsView": null,
            "UpdatePublishedProcedureName": "usp_IM_UpdateIMVendorPublishedById",
            "TabName": null,
            "APITemplateName": "Vendor",
            "LabelTooltip": "Enter the last name of the contact person at your vendor's company.",
            "IsHideFieldInUI": false
        },
        {
            "Type": "textarea",
            "FormField": "VendorAddress",
            "Label": "Address",
            "PlaceHolder": "Enter Address",
            "MasterModuleCode": null,
            "MasterAPIUrl": null,
            "Required": true,
            "RequiredErrorMessage": "Enter Address",
            "LengthErrorMessage": "Address cannot be more than 512 characters",
            "Pattern1": "^[^<>]*$",
            "Pattern1ErrorMessage": "Invalid Address",
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": 512,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": null,
            "ArrayListName": null,
            "ParentFieldName": null,
            "IsView": null,
            "UpdatePublishedProcedureName": "usp_IM_UpdateIMVendorPublishedById",
            "TabName": null,
            "APITemplateName": "Vendor",
            "LabelTooltip": "Input the office location details of the vendor.",
            "IsHideFieldInUI": false
        },
        {
            "Type": "number",
            "FormField": "PinCode",
            "Label": "Pin Code",
            "PlaceHolder": "Enter Pin Code",
            "MasterModuleCode": null,
            "MasterAPIUrl": null,
            "Required": true,
            "RequiredErrorMessage": "Enter Pin Code",
            "LengthErrorMessage": "Pin Code cannot be more than 6 characters",
            "Pattern1": "^\\d{6}$",
            "Pattern1ErrorMessage": "Invalid Pin Code",
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": 6,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": null,
            "ArrayListName": null,
            "ParentFieldName": null,
            "IsView": null,
            "UpdatePublishedProcedureName": "usp_IM_UpdateIMVendorPublishedById",
            "TabName": null,
            "APITemplateName": "Vendor",
            "LabelTooltip": "Enter your vendor pincode.",
            "IsHideFieldInUI": false
        },
        {
            "Type": "dropdown",
            "FormField": "CityId",
            "Label": "City",
            "PlaceHolder": "Select City",
            "MasterModuleCode": "City-296",
            "MasterAPIUrl": "GetDataBySearch",
            "Required": true,
            "RequiredErrorMessage": "Select City",
            "LengthErrorMessage": null,
            "Pattern1": null,
            "Pattern1ErrorMessage": null,
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": null,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": null,
            "ArrayListName": null,
            "ParentFieldName": "StateId",
            "IsView": null,
            "UpdatePublishedProcedureName": "usp_IM_UpdateIMVendorPublishedById",
            "TabName": null,
            "APITemplateName": "Vendor",
            "LabelTooltip": "Select the city where your vendor is located.",
            "IsHideFieldInUI": false
        },
        {
            "Type": "dropdown",
            "FormField": "StateId",
            "Label": "State",
            "PlaceHolder": "Select State",
            "MasterModuleCode": "State",
            "MasterAPIUrl": "GetMasters",
            "Required": true,
            "RequiredErrorMessage": "Select State",
            "LengthErrorMessage": null,
            "Pattern1": null,
            "Pattern1ErrorMessage": null,
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": null,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": null,
            "ArrayListName": null,
            "ParentFieldName": null,
            "IsView": null,
            "UpdatePublishedProcedureName": "usp_IM_UpdateIMVendorPublishedById",
            "TabName": null,
            "APITemplateName": "Vendor",
            "LabelTooltip": "Select the state where your vendor is located.",
            "IsHideFieldInUI": false
        },
        {
            "Type": "text",
            "FormField": "GSTINNumber",
            "Label": "GSTIN Number",
            "PlaceHolder": "Enter GSTIN Number",
            "MasterModuleCode": null,
            "MasterAPIUrl": null,
            "Required": false,
            "RequiredErrorMessage": "Enter GSTIN Number",
            "LengthErrorMessage": "GSTIN Number cannot be more than 15 characters",
            "Pattern1": "^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$",
            "Pattern1ErrorMessage": "Invalid GSTIN Number",
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": 15,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": null,
            "ArrayListName": null,
            "ParentFieldName": null,
            "IsView": null,
            "UpdatePublishedProcedureName": "usp_IM_UpdateIMVendorPublishedById",
            "TabName": null,
            "APITemplateName": "Vendor",
            "LabelTooltip": "Input GSTIN number of your vendor.",
            "IsHideFieldInUI": false
        },
        {
            "Type": "phonenumber",
            "FormField": "LandLinePhoneNo",
            "Label": "Phone Number",
            "PlaceHolder": "Enter Phone Number",
            "MasterModuleCode": null,
            "MasterAPIUrl": null,
            "Required": false,
            "RequiredErrorMessage": "Enter Phone Number",
            "LengthErrorMessage": "Phone Number cannot be more than 18 characters",
            "Pattern1": "^[\\+]\\d{1,3}-\\d{2,4}-\\d{5,8}$",
            "Pattern1ErrorMessage": "Invalid Phone Number",
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": 18,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": null,
            "ArrayListName": null,
            "ParentFieldName": null,
            "IsView": null,
            "UpdatePublishedProcedureName": "usp_IM_UpdateIMVendorPublishedById",
            "TabName": null,
            "APITemplateName": "Vendor",
            "LabelTooltip": "Enter your vendor's landline number.",
            "IsHideFieldInUI": false
        },
        {
            "Type": "mobile",
            "FormField": "Mobile",
            "Label": "Mobile Number",
            "PlaceHolder": "Enter Mobile Number",
            "MasterModuleCode": null,
            "MasterAPIUrl": null,
            "Required": true,
            "RequiredErrorMessage": "Enter Mobile Number",
            "LengthErrorMessage": "Mobile Number cannot be more than 10 characters",
            "Pattern1": "^[6-9][0-9]{9}$",
            "Pattern1ErrorMessage": "Invalid Mobile Number (Start with 6/7/8/9 or length is 10. Ex. 9123456789)",
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": 10,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": null,
            "ArrayListName": null,
            "ParentFieldName": null,
            "IsView": null,
            "UpdatePublishedProcedureName": "usp_IM_UpdateIMVendorPublishedById",
            "TabName": null,
            "APITemplateName": "Vendor",
            "LabelTooltip": "Enter your vendor's mobile number.",
            "IsHideFieldInUI": false
        },
        {
            "Type": "email",
            "FormField": "ContactEmail",
            "Label": "Contact Email",
            "PlaceHolder": "Enter Contact Email",
            "MasterModuleCode": null,
            "MasterAPIUrl": null,
            "Required": true,
            "RequiredErrorMessage": "Enter Contact Email",
            "LengthErrorMessage": "Contact Email cannot be more than 64 characters",
            "Pattern1": "^[a-zA-Z0-9][a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$",
            "Pattern1ErrorMessage": "Invalid Contact Email",
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": 64,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": null,
            "ArrayListName": null,
            "ParentFieldName": null,
            "IsView": null,
            "UpdatePublishedProcedureName": "usp_IM_UpdateIMVendorPublishedById",
            "TabName": null,
            "APITemplateName": "Vendor",
            "LabelTooltip": "Enter your vendor's email address.",
            "IsHideFieldInUI": false
        },
        {
            "Type": "textarea",
            "FormField": "VendorDetails",
            "Label": "Vendor Details",
            "PlaceHolder": "Enter Vendor Details",
            "MasterModuleCode": null,
            "MasterAPIUrl": null,
            "Required": false,
            "RequiredErrorMessage": "Enter Vendor Details",
            "LengthErrorMessage": "Vendor Details cannot be more than 128 characters",
            "Pattern1": "^[^<>]*$",
            "Pattern1ErrorMessage": "Invalid Vendor Details",
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": 128,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": null,
            "ArrayListName": null,
            "ParentFieldName": null,
            "IsView": null,
            "UpdatePublishedProcedureName": "usp_IM_UpdateIMVendorPublishedById",
            "TabName": null,
            "APITemplateName": "Vendor",
            "LabelTooltip": "Provide any additional notes about this vendor.",
            "IsHideFieldInUI": false
        },
        {
            "Type": "image",
            "FormField": "VendorLogo",
            "Label": "Vendor Logo",
            "PlaceHolder": "Enter Vendor Logo",
            "MasterModuleCode": null,
            "MasterAPIUrl": null,
            "Required": false,
            "RequiredErrorMessage": "Enter Vendor Logo",
            "LengthErrorMessage": null,
            "Pattern1": "^.+\\.(([jJ][pP][gG])|([pP][nN][gG])|([jJ][pP][eE][gG]))$",
            "Pattern1ErrorMessage": "Please upload a jpg or png image.",
            "Pattern2": null,
            "Pattern2ErrorMessage": "Image should not be greater than 5MB.",
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": null,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": "5120",
            "IsNonEditable": false,
            "DateFormat": null,
            "ArrayListName": null,
            "ParentFieldName": null,
            "IsView": null,
            "UpdatePublishedProcedureName": "usp_IM_UpdateIMVendorPublishedById",
            "TabName": null,
            "APITemplateName": "Vendor",
            "LabelTooltip": "Add your vendor logo.",
            "IsHideFieldInUI": false
        }
    ],
    "ChildDataList": null,
    "FiltersDataList": [
        {
            "Type": "text",
            "FormField": "SearchWord",
            "Label": "Search",
            "PlaceHolder": "Enter Search Word",
            "MasterModuleCode": null,
            "MasterAPIUrl": null,
            "Required": false,
            "RequiredErrorMessage": null,
            "LengthErrorMessage": null,
            "Pattern1": "^[^<>]*$",
            "Pattern1ErrorMessage": "Invalid Search Word",
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": 128,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": null,
            "ArrayListName": null,
            "ParentFieldName": null
        },
        {
            "Type": "text",
            "FormField": "SearchWord",
            "Label": "Search",
            "PlaceHolder": "Enter Search Word",
            "MasterModuleCode": null,
            "MasterAPIUrl": null,
            "Required": false,
            "RequiredErrorMessage": null,
            "LengthErrorMessage": null,
            "Pattern1": "^[^<>]*$",
            "Pattern1ErrorMessage": "Invalid Search Word",
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": 128,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": null,
            "ArrayListName": null,
            "ParentFieldName": null
        },
        {
            "Type": "text",
            "FormField": "SearchWord",
            "Label": "Search",
            "PlaceHolder": "Enter Search Word",
            "MasterModuleCode": null,
            "MasterAPIUrl": null,
            "Required": false,
            "RequiredErrorMessage": null,
            "LengthErrorMessage": null,
            "Pattern1": "^[^<>]*$",
            "Pattern1ErrorMessage": "Invalid Search Word",
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": 128,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": null,
            "ArrayListName": null,
            "ParentFieldName": null
        },
        {
            "Type": "date",
            "FormField": "FromDate",
            "Label": "From Date",
            "PlaceHolder": "DD/MM/YYYY",
            "MasterModuleCode": null,
            "MasterAPIUrl": null,
            "Required": false,
            "RequiredErrorMessage": null,
            "LengthErrorMessage": null,
            "Pattern1": null,
            "Pattern1ErrorMessage": null,
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": null,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": "dd/MM/yyyy",
            "ArrayListName": null,
            "ParentFieldName": null
        },
        {
            "Type": "date",
            "FormField": "ToDate",
            "Label": "To Date",
            "PlaceHolder": "DD/MM/YYYY",
            "MasterModuleCode": null,
            "MasterAPIUrl": null,
            "Required": false,
            "RequiredErrorMessage": null,
            "LengthErrorMessage": null,
            "Pattern1": null,
            "Pattern1ErrorMessage": null,
            "Pattern2": null,
            "Pattern2ErrorMessage": null,
            "Pattern3": null,
            "Pattern3ErrorMessage": null,
            "MinLength": null,
            "MaxLength": null,
            "MaxRange": null,
            "MinRange": null,
            "RangeErrorMessage": null,
            "FileSize": null,
            "IsNonEditable": false,
            "DateFormat": "dd/MM/yyyy",
            "ArrayListName": null,
            "ParentFieldName": null
        }
    ]
}